// Auto-generated by scripts/generate-api-client.js.
// Do not edit manually. Regenerate via: node scripts/generate-api-client.js

(function (globalScope) {
  'use strict';

  function createMarketRankClient(config = {}) {
    const baseUrl = String(config.baseUrl || '').replace(/\/$/, '');
    let token = config.token || '';
    let moderatorKey = config.moderatorKey || '';

    async function request(method, route, body, options = {}) {
      const headers = {
        ...(options.headers || {}),
        'content-type': 'application/json'
      };

      const authToken = options.token || token;
      if (authToken) headers.authorization = 'Bearer ' + authToken;

      const modKey = options.moderatorKey || moderatorKey;
      if (modKey) headers['x-moderator-key'] = modKey;

      const url = baseUrl + route;
      const res = await fetch(url, {
        method,
        headers,
        body: body === undefined ? undefined : JSON.stringify(body)
      });

      let json = null;
      try {
        json = await res.json();
      } catch (_) {
        json = null;
      }

      if (!res.ok) {
        const error = new Error((json && json.error) || ('Request failed: ' + res.status));
        error.status = res.status;
        error.payload = json;
        throw error;
      }

      return json;
    }

    return {
      setToken(nextToken) { token = nextToken || ''; },
      setModeratorKey(nextKey) { moderatorKey = nextKey || ''; },

  /**
   * POST /api/auth/email/verify/confirm
   * Public endpoint.
   */
  async confirmEmailVerification(body = {}, options = {}) {
    return request('POST', '/api/auth/email/verify/confirm', body, options);
  },

  /**
   * POST /api/auth/password/reset/confirm
   * Public endpoint.
   */
  async confirmPasswordReset(body = {}, options = {}) {
    return request('POST', '/api/auth/password/reset/confirm', body, options);
  },

  /**
   * POST /api/moderation/appeal
   * Requires bearer auth token.
   */
  async createAppeal(body = {}, options = {}) {
    return request('POST', '/api/moderation/appeal', body, options);
  },

  /**
   * POST /api/moderation/ban
   * Public endpoint.
   * Requires moderator key.
   */
  async createBan(body = {}, options = {}) {
    return request('POST', '/api/moderation/ban', body, options);
  },

  /**
   * POST /api/moderation/flag
   * Requires bearer auth token.
   */
  async createFlag(body = {}, options = {}) {
    return request('POST', '/api/moderation/flag', body, options);
  },

  /**
   * POST /api/predictions
   * Requires bearer auth token.
   */
  async createPrediction(body = {}, options = {}) {
    return request('POST', '/api/predictions', body, options);
  },

  /**
   * GET /api/health
   * Public endpoint.
   */
  async health(options = {}) {
    return request('GET', '/api/health', undefined, options);
  },

  /**
   * GET /api/leaderboard
   * Public endpoint.
   */
  async leaderboard(options = {}) {
    return request('GET', '/api/leaderboard', undefined, options);
  },

  /**
   * POST /api/auth/login
   * Public endpoint.
   */
  async login(body = {}, options = {}) {
    return request('POST', '/api/auth/login', body, options);
  },

  /**
   * POST /api/auth/logout
   * Requires bearer auth token.
   */
  async logout(body = {}, options = {}) {
    return request('POST', '/api/auth/logout', body, options);
  },

  /**
   * GET /api/metrics
   * Public endpoint.
   * Requires moderator key.
   */
  async metrics(options = {}) {
    return request('GET', '/api/metrics', undefined, options);
  },

  /**
   * GET /api/moderation/dashboard
   * Public endpoint.
   * Requires moderator key.
   */
  async moderationDashboard(options = {}) {
    return request('GET', '/api/moderation/dashboard', undefined, options);
  },

  /**
   * POST /api/auth/register
   * Public endpoint.
   */
  async register(body = {}, options = {}) {
    return request('POST', '/api/auth/register', body, options);
  },

  /**
   * POST /api/auth/email/verify/request
   * Public endpoint.
   */
  async requestEmailVerification(body = {}, options = {}) {
    return request('POST', '/api/auth/email/verify/request', body, options);
  },

  /**
   * POST /api/auth/password/reset/request
   * Public endpoint.
   */
  async requestPasswordReset(body = {}, options = {}) {
    return request('POST', '/api/auth/password/reset/request', body, options);
  }
    };
  }

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = { createMarketRankClient };
  } else {
    globalScope.createMarketRankClient = createMarketRankClient;
  }
})(typeof globalThis !== 'undefined' ? globalThis : window);
